meta_product_name: "Moveable Feasts"
meta_title: "Moveable Feasts - Meet new people by organizing or joining private culinary events"
meta_description: "Once you sign up you can host a dinner or join a meal. Our goal is to put you in touch with delicious meals, potential future friends, and good spirits."
meta_image: "friends.jpg" # should exist in `app/assets/images/`
